image: willhallonline/ansible:2.12-ubuntu-jammy

stages:
  - deploy

deploy_ansible:
  stage: deploy
  tags:
    - ansible_windows     # â† Tag deines Docker-Runners
  only:
    - main
  before_script:
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$ANSIBLE_SSH_KEY" | tr -d '\r' | ssh-add -
    - ssh-keyscan -H 192.168.1.130 >> ~/.ssh/known_hosts
  script:
    - ansible-playbook main.yml -i inventory